### PR TITLE
Refactored code

### PR DESCRIPTION
**Pull request by ghost**
Refactored code to make intention more clear.
Changed database trait implementation from main.rs to application layer. The application layer brings together the domain and infrastructure.

### CODE REVIEW

**Comment by ghost** [comment]
Thank you for example project, was looking for ddd example like this.

**Comment by jdomenechb** [comment]
First of all, thanks for doing this. I appreciate all feedback, and yours beside productive, was specially nice :) 

Having said that, I need to say that, although being also a good approach and a perfect valid option, I don't really share your approach of having different use cases inside a Handler with different methods. 

Besides admitting that in that simple application it makes perfect sense, I think that having separated use cases helps when moving to other design implementations, like CommandBus or CQRS, Besides, it helps following the Simple Responsibility Principle from SOLID.

You must have into account also that my main language is not Rust. DDD generally is easier to be applied in object oriented languages, a feature which Rust lacks, and that could have an influence on my way of thinking.

I don't want to discard this pull request at all - as I said, your approach is also perfectly valid, and depending of the person looking at it might even consider its better than the original. But given the reasons I exposed, for now, I prefer to not merge it either.

That's why I would love to hear your opinion on that matter, and reach an agreement altogether, or having a constructive discussion ^^  Again, thank you for your contribution, it's always lovely to receive feedback in any way!

**Comment by ghost** [comment]
CQRS :-) , that's why you had handler/request naming. I was wondering why you had that. I could use CommandHandler and QueryHandler naming to make it more explicit?

I don't think DDD is necessarily more easy in a object orientated language, it is just different in Rust which uses [Composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance).

**Comment by jdomenechb** [comment]
That would be a nice thing to try :)

I'm sorry, when I said "easier" I was referring that in my opinion, as DDD principles were firstly built on top of OOP languages, it's natural that more doubts will arise in a language not object oriented when doing a typical implementation. Of course, in those cases, things would be done a little different.

**Review by auvipy — APPROVED** [review]
LGTM!

**Pull request closed without merging**
